### ISSUE TITLE
Multiple timers are not working well

### ISSUE THREAD

**Issue by olegafx** [JacobBennett/VoiceTimer#1]
Say `Set timer for 60 seconds`
Wait for some time
Say `Set timer for 60 seconds`

Expected: first timer gone, second one set.
Reality: jumping animation between two timers

Chrome 51, OSX

Good job, btw 👍

**Comment by thomas-leroy** [comment]
I had a great time trying to `set timer for -0 seconds` or `undefined seconds`, but the only issue I've found was was multiple times at once too.

Nice job, really funny when cooking :+1:

**Comment by JacobBennett** [comment]
@thomas-leroy Thanks for using it! :) I never thought to try undefined or 0, that is amazing 👍  Will have to try that myself.

I need a way to clear out the timer. Being that this is a hobby project, I haven't had much time to mess with it. If you wan to submit a PR I'll pull it in!

**Comment by thomas-leroy** [comment]
Done ; )
